services:
  api-service:
    build: .
    container_name: api-service
    environment:
      - APP_MODE=${APP_MODE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PINATA_TOKEN=${PINATA_TOKEN}
      - PINATA_GATEWAY=${PINATA_GATEWAY}
      - PINATA_LINK_EXPIRATION=${PINATA_LINK_EXPIRATION}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
    ports:
      - 1323:1323
    restart: on-failure
    networks:
      - my-network
    depends_on:
      - mysql-service

  mysql-service:
    image: mysql:latest
    container_name: mysql-service
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - 3306
    volumes:
      - ${APP_VOLUME}:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
