// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	context "context"
	ads "go-ads-management/businesses/ads"

	gorm "gorm.io/gorm"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, adsReq
func (_m *Repository) Create(ctx context.Context, adsReq *ads.Domain) (ads.Domain, error) {
	ret := _m.Called(ctx, adsReq)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 ads.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ads.Domain) (ads.Domain, error)); ok {
		return rf(ctx, adsReq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ads.Domain) ads.Domain); ok {
		r0 = rf(ctx, adsReq)
	} else {
		r0 = ret.Get(0).(ads.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ads.Domain) error); ok {
		r1 = rf(ctx, adsReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForceDelete provides a mock function with given fields: ctx, id
func (_m *Repository) ForceDelete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ForceDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *Repository) GetAll(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCategory provides a mock function with given fields: ctx, categoryID
func (_m *Repository) GetByCategory(ctx context.Context, categoryID int) (*gorm.DB, error) {
	ret := _m.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCategory")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*gorm.DB, error)); ok {
		return rf(ctx, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *gorm.DB); ok {
		r0 = rf(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *Repository) GetByID(ctx context.Context, id int) (ads.Domain, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 ads.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (ads.Domain, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) ads.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(ads.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUser provides a mock function with given fields: ctx
func (_m *Repository) GetByUser(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTrashed provides a mock function with given fields: ctx
func (_m *Repository) GetTrashed(ctx context.Context) (*gorm.DB, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTrashed")
	}

	var r0 *gorm.DB
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*gorm.DB, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *gorm.DB); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *Repository) Restore(ctx context.Context, id int) (ads.Domain, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 ads.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (ads.Domain, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) ads.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(ads.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, adsReq, id
func (_m *Repository) Update(ctx context.Context, adsReq *ads.Domain, id int) (ads.Domain, error) {
	ret := _m.Called(ctx, adsReq, id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 ads.Domain
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ads.Domain, int) (ads.Domain, error)); ok {
		return rf(ctx, adsReq, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ads.Domain, int) ads.Domain); ok {
		r0 = rf(ctx, adsReq, id)
	} else {
		r0 = ret.Get(0).(ads.Domain)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ads.Domain, int) error); ok {
		r1 = rf(ctx, adsReq, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
