// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import (
	models "go-ads-management/models"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetByEmail provides a mock function with given fields: userInput
func (_m *UserRepository) GetByEmail(userInput models.LoginInput) (models.User, error) {
	ret := _m.Called(userInput)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(models.LoginInput) (models.User, error)); ok {
		return rf(userInput)
	}
	if rf, ok := ret.Get(0).(func(models.LoginInput) models.User); ok {
		r0 = rf(userInput)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(models.LoginInput) error); ok {
		r1 = rf(userInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserInfo provides a mock function with given fields: id
func (_m *UserRepository) GetUserInfo(id string) (models.User, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: userInput
func (_m *UserRepository) Register(userInput models.RegisterInput) (models.User, error) {
	ret := _m.Called(userInput)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(models.RegisterInput) (models.User, error)); ok {
		return rf(userInput)
	}
	if rf, ok := ret.Get(0).(func(models.RegisterInput) models.User); ok {
		r0 = rf(userInput)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(models.RegisterInput) error); ok {
		r1 = rf(userInput)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
